name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    name: Build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('yarn.lock') }}
      - run: >
          yarn config set
          npmScopes.siteimprove.npmAuthToken
          ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn test
